#!/bin/sh /etc/rc.common
USE_PROCD=1
START=95
STOP=01
NAME=v2ray
start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/v2ray -c /etc/config/v2ray.json
    procd_set_param respawn
    procd_set_param pidfile /var/run/v2ray.pid
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}